version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "python"
enabled = true

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true